---
# Sets the lab env up for Streams BF labs.
#
# For now, just resets the Java alternatives back to Java 21.
#
- name: Ensure Java is versioned correctly for Streams BF labs
  become: yes
  ansible.builtin.command:
    cmd: /usr/sbin/alternatives --set {{ item }} java-21-openjdk.x86_64
  loop:
    - java
    - javac
...
