---
#
# TODO: fix .m2/settings.xml
#
- name: Ensure Java is versioned correctly for AD482
  become: yes
  ansible.builtin.command:
    cmd: /usr/sbin/alternatives --set {{ item }} java-11-openjdk.x86_64
  loop:
    - java
    - javac

- name: Load the python alternative
  ansible.builtin.slurp:
    src: /var/lib/alternatives/python
  register: altpy

- name: Install an alternative for python3.9 if not found
  become: yes
  ansible.builtin.command:
    cmd: /usr/sbin/alternatives --install /usr/bin/python python /usr/bin/python3.9 15
  when:
    - not "/usr/bin/python3.9" in (altpy['content'] | b64decode)

- name: Activate the Python alternative for AD482
  become: yes
  ansible.builtin.command:
    cmd: /usr/sbin/alternatives --set python /usr/bin/python3.9

- name: Ensure credentials for internal registry are active
  containers.podman.podman_login:
    registry: registry.ocp4.example.com:8443
    username: developer
    password: developer

- name: Mirror the quay.io images to internal registry, fixing format along the way
  ansible.builtin.command:
    cmd: /usr/bin/skopeo copy --format=v2s2 docker://quay.io/redhattraining/{{ item }} registry.ocp4.example.com:8443/redhattraining/{{ item }}
  loop:
    - ad482-ch05s04-connect-cluster:latest
    - ad482-ch05s06-connect-cluster:latest
    - ad482-ch05s08-connect-cluster:latest
    - ad482-postgresql:latest

# patch scripts ad482/connect_connectors.py ad482/connect_debezium.py ad482/connect_transformation.py
...
