---
removed_sources:
  - do280-catalog
  - do280-catalog-cs
  - do288-catalog-cs
  - do370-catalog-cs
  - do380-catalog-cs
  - lb0004-catalog-cs
registry_server: registry.redhat.io
catalog_sources:
  - name: redhat-operators
    displ: Red Hat Operators
    image: "{{ registry_server }}/redhat/redhat-operator-index:v{{ ocp_maj }}"
  - name: certified-operators
    displ: Certified Operators
    image: "{{ registry_server }}/redhat/certified-operator-index:v{{ ocp_maj }}"
  - name: community-operators
    displ: Community Operators
    image: "{{ registry_server }}/redhat/community-operator-index:v{{ ocp_maj }}"
...
