apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: bf-brokers
spec:
  kafka:
    version: 3.7.0
    replicas: 3
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 2
    listeners:
      - name: plain
        type: internal
        port: 9092
        tls: false
      - name: tls
        type: internal
        port: 9093
        tls: true
      - name: external
        type: route
        port: 9094
        tls: true
    storage:
      deleteClaim: true
      type: persistent-claim
      size: 2Gi
    config:
      inter.broker.protocol.version: "3.7"
      log.message.format.version: "3.7"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.create.topics.enable: "false"
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
    storage:
      deleteClaim: true
      type: persistent-claim
      size: 1Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
