apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  labels:
    strimzi.io/cluster: "bf-brokers"
spec:
  partitions: 15
  replicas: 3
  config:
    retention.ms: 604800000   # 7 days
    segment.bytes: 10485760   # 10MiB
