---
# A simplistic inventory for the classroom VMs.
all:
  hosts:
    workstation.lab.example.com:
      ansible_connection: local
    utility.lab.example.com:
      ansible_user: lab
    bastion.lab.example.com:
      ansible_user: root
  vars:
    # OpenShift versions.
    ocp_maj: "4.18"
    ocp_z: "4.18.6"

    # Operators that need to be installed.
    added_operators:
      - catalog: redhat-operators
        package: amq-streams
        channel: amq-streams-2.9.x
        namespace: openshift-operators
        desired_csv: amqstreams.v2.9.3-1
        og_namespaces: []
        approval: Manual
      - catalog: redhat-operators
        package: service-registry-operator
        channel: 2.x
        namespace: openshift-operators
        desired_csv: service-registry-operator.v2.6.13-r2-0.1763986602.p
        og_namespaces: []
        approval: Manual
      - catalog: redhat-operators
        package: elasticsearch-operator
        channel: stable-5.8
        namespace: openshift-operators-redhat
        desired_csv: elasticsearch-operator.v5.8.21
        og_namespaces: []
        approval: Manual

    vrfy_cat: "{{ added_operators[0].catalog }}"
    vrfy_pkg: "{{ added_operators[0].package }}"
    vrfy_chn: "{{ added_operators[0].channel }}"
    vrfy_csv: "{{ added_operators[0].desired_csv }}"

    # Some cleanup here.
    removed_operators:
      - sub_nspc: openshift-operators
        sub_name: openshift-pipelines-operator
        csv_kill: yes
        csv_name: openshift-pipelines-operator-rh.v1.18.1
        pre_cleanup:
          - kind: openshiftpipelinesascodes
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonaddons
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonchains
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonconfigs
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonhubs
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektoninstallersets
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonpipelines
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonresults
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektontriggers
            apiv: operator.tekton.dev/v1alpha1
        add_cleanup:
          - openshiftpipelinesascodes.operator.tekton.dev
          - tektonaddons.operator.tekton.dev
          - tektonchains.operator.tekton.dev
          - tektonconfigs.operator.tekton.dev
          - tektonhubs.operator.tekton.dev
          - tektoninstallersets.operator.tekton.dev
          - tektonpipelines.operator.tekton.dev
          - tektonresults.operator.tekton.dev
          - tektontriggers.operator.tekton.dev

    # The list of OpenShift clusters check-env will try to connect to.
    clusters:
      - ocp4
...
