---
# A simplistic inventory for the classroom VMs.
all:
  hosts:
    workstation.lab.example.com:
      ansible_connection: local
    utility.lab.example.com:
      ansible_user: lab
    bastion.lab.example.com:
      ansible_user: root
  vars:
    # OpenShift versions.
    ocp_maj: "4.14"
    ocp_z: "4.14.0"

    # Operator that needs to be installed.
    op_cat: redhat-operators
    op_pkg: amq-streams
    op_chn: stable
    op_nsp: openshift-operators
    desired_csv: amqstreams.v2.7.0-4

    # Some cleanup here.
    removed_operators:
      - sub_nspc: openshift-operators
        sub_name: openshift-pipelines-operator
        csv_name: foobar
        pre_cleanup:
          - kind: openshiftpipelinesascodes
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonaddons
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonchains
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonconfigs
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonhubs
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektoninstallersets
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonpipelines
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektonresults
            apiv: operator.tekton.dev/v1alpha1
          - kind: tektontriggers
            apiv: operator.tekton.dev/v1alpha1
        add_cleanup:
          - openshiftpipelinesascodes.operator.tekton.dev
          - tektonaddons.operator.tekton.dev
          - tektonchains.operator.tekton.dev
          - tektonconfigs.operator.tekton.dev
          - tektonhubs.operator.tekton.dev
          - tektoninstallersets.operator.tekton.dev
          - tektonpipelines.operator.tekton.dev
          - tektonresults.operator.tekton.dev
          - tektontriggers.operator.tekton.dev

    # The list of OpenShift clusters check-env will try to connect to.
    clusters:
      - ocp4
...
