---
# A simplistic inventory for the classroom VMs.
all:
  hosts:
    workstation.lab.example.com:
      ansible_connection: local
    utility.lab.example.com:
      ansible_user: lab
    bastion.lab.example.com:
      ansible_user: root
  vars:
    # OpenShift versions.
    ocp_maj: "4.14"
    ocp_z: "4.14.0"

    # Operator that needs to be installed.
    op_cat: redhat-operators
    op_pkg: amq-streams
    op_chn: stable
    op_nsp: openshift-operators
    desired_csv: amqstreams.v2.7.0-4

    # Some cleanup here.
    removed_operators:
      - sub_nspc: openshift-operators
        sub_name: openshift-pipelines-operator
        csv_name: foobar
        pre_cleanup:
           - kind: openshiftpipelinesascodes
             apiv: operator.tekton.dev/v1alpha1
           - kind: tektonaddons
             apiv: operator.tekton.dev/v1alpha1
           - kind: tektonchains
             apiv: operator.tekton.dev/v1alpha1
           - kind: tektonconfigs
             apiv: operator.tekton.dev/v1alpha1
           - kind: tektonhubs
             apiv: operator.tekton.dev/v1alpha1
           - kind: tektoninstallersets
             apiv: operator.tekton.dev/v1alpha1
           - kind: tektonpipelines
             apiv: operator.tekton.dev/v1alpha1
           - kind: tektonresults
             apiv: operator.tekton.dev/v1alpha1
           - kind: tektontriggers
             apiv: operator.tekton.dev/v1alpha1
           - kind: repositories
             apiv: pipelinesascode.tekton.dev/v1alpha1
           - kind: resolutionrequests
             apiv: resolution.tekton.dev/v1beta1
           - kind: clustertasks
             apiv: tekton.dev/v1beta1
           - kind: customruns
             apiv: tekton.dev/v1beta1
           - kind: pipelineruns
             apiv: tekton.dev/v1
           - kind: pipelines
             apiv: tekton.dev/v1
           - kind: stepactions
             apiv: tekton.dev/v1alpha1
           - kind: taskruns
             apiv: tekton.dev/v1
           - kind: tasks
             apiv: tekton.dev/v1
           - kind: verificationpolicies
             apiv: tekton.dev/v1alpha1
           - kind: clusterinterceptors
             apiv: triggers.tekton.dev/v1alpha1
           - kind: clustertriggerbindings
             apiv: triggers.tekton.dev/v1beta1
           - kind: eventlisteners
             apiv: triggers.tekton.dev/v1beta1
           - kind: interceptors
             apiv: triggers.tekton.dev/v1alpha1
           - kind: triggerbindings
             apiv: triggers.tekton.dev/v1beta1
           - kind: triggers
             apiv: triggers.tekton.dev/v1beta1
           - kind: triggertemplates
             apiv: triggers.tekton.dev/v1beta1

    # The list of OpenShift clusters check-env will try to connect to.
    clusters:
      - ocp4
...
