---
- name: Pre-flight checks only.
  hosts: workstation.lab.example.com
  gather_subset: min
  become: no
  tasks:
    - include_role:
        name: check-env
        apply:
          tags: check
      tags: check
    - include_role:
        name: fix-operators
        apply:
          tags: fix
      tags: fix
    - include_role:
        name: remove-operators
        apply:
          tags: prep
      loop: "{{ removed_operators }}"
      loop_control:
        loop_var: role
      tags: prep
    - include_role:
        name: deploy-operators
        apply:
          tags: prep
      loop: "{{ added_operators }}"
      loop_control:
        loop_var: role
      tags: prep
    - include_role:
        name: install-labs
        apply:
          tags: workstation
      tags: workstation
    - include_role:
        name: prep-workspace
        apply:
          tags: workstation
      tags: workstation
...
